remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-readme-index
title: [YouTube MadeForKids Checker]
description: [Create custom exclusion list for better performance on Google Ads]
show_downloads: true
github:
  macOS: https://github.com/seexmax/YouTube-MadeForKids-Checker/releases/download/v1.0.0/YouTube-MadeForKids-Checker.v1.0.macOS.zip
  Windows: https://github.com/seexmax/YouTube-MadeForKids-Checker/releases/download/v1.0.0/YouTube-MadeForKids-Checker.v1.0.Win.zip
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false